version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-network
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
    container_name: server
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mern

    ports:
      - "9000:9000"
    networks:
      - mern-network
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mern-network
    depends_on:
      - server

networks:
  mern-network:
    driver: bridge
